<?php
$treedata = array(
    1=>array(
        'id'=>'ppt',
        'name'=>'PPT',
        'userid'=>['wangxl','lix','admin'],
        'children'=>array(
            [
                'id'=>'ppt_avocent',
                'name'=>'AVOCENT产品',
                'userid'=>['wangxl','lix','admin','wangl','zanghb','liub']
            ],
            [
                'id'=>'ppt_ziyou',
                'name'=>'自有软件产品',
                'userid'=>['wangxl','lix','admin','zanghb','songjc','yanxj','hunjb','liub','wangl']
            ],
            [
                'id'=>'ppt_yingjian',
                'name'=>'自有硬件产品',
                'userid'=>['wangxl','lix','admin','wangl','zanghb','liub']
            ],
        )
    ),
    2=>array(
        'id'=>'anli',
        'name'=>'案例及方案',
        'userid'=>['wangxl','lix','admin'],
        'children'=>array(
            [
                'id'=>'anli_avocent',
                'name'=>'AVOCENT产品',
                'userid'=>['wangxl','lix','admin','wangl','zanghb','liub']
            ],
            [
                'id'=>'anli_ziyou',
                'name'=>'自有软件产品',
                'userid'=>['wangxl','lix','admin','zanghb','songjc','yanxj','hunjb','liub','wangl']
            ],
            [
                'id'=>'anli_yingjian',
                'name'=>'自有硬件产品',
                'userid'=>['wangxl','lix','admin','wangl','zanghb','liub']
            ],
        )
    ),
    3=>array(
        'id'=>'caiye',
        'name'=>'产品彩页',
        'userid'=>['wangxl','lix','admin'],
        'children'=>array(
            [
                'id'=>'caiye_avocent',
                'name'=>'AVOCENT彩页',
                'userid'=>['wangxl','lix','admin','wangl','zanghb','liub']
            ],
            [
                'id'=>'caiye_ziyou',
                'name'=>'自有软件产品彩页',
                'userid'=>['wangxl','lix','admin','zanghb','songjc','yanxj','hunjb','liub','wangl']
            ],
            [
                'id'=>'caiye_yingjian',
                'name'=>'自有硬件产品彩页',
                'userid'=>['wangxl','lix','admin','wangl','zanghb','liub']
            ],
        )
    ),
    4=>array(
        'id'=>'zhaopian',
        'name'=>'产品照片',
        'userid'=>['wangxl','lix','admin','zanghb','songjc','yanxj','hunjb','liub','wangl']
    ),
    5=>array(
        'id'=>'shouce',
        'name'=>'昕辰产品白皮书、使用手册等',
        'userid'=>['wangxl','lix','admin'],
        'children'=>array(
            [
                'id'=>'shouce_ziyou',
                'name'=>'自有软件产品',
                'userid'=>['wangxl','lix','admin','zanghb','songjc','yanxj','hunjb','liub','wangl'],
                'children'=>array(
                            [
                                'id'=>'shouce-ziyou-logsys',
                                'name'=>'LOGSYS',
                                'userid'=>['wangxl','lix','admin','songjc','wangl'],
                            ],
                            [
                                'id'=>'shouce-ziyou-udcs',
                                'name'=>'UDCS',
                                'userid'=>['wangxl','lix','admin','songjc','wangl'],
                            ],
                            [
                                'id'=>'shouce-ziyou-eim',
                                'name'=>'EIM',
                                'userid'=>['wangxl','lix','admin','yanxj','wangl'],
                            ],
                            [
                                'id'=>'shouce-ziyou-dra',
                                'name'=>'DRA',
                                'userid'=>['wangxl','lix','admin','yanxj','wangl'],
                            ],
                            [
                                'id'=>'shouce-ziyou-ais',
                                'name'=>'AIS',
                                'userid'=>['wangxl','lix','admin','hunjb','wangl'],
                            ],
                            [
                                'id'=>'shouce-ziyou-iphm',
                                'name'=>'IPHM',
                                'userid'=>['wangxl','lix','admin','hunjb','wangl'],
                            ],
                            [
                                'id'=>'shouce-ziyou-nts',
                                'name'=>'NTS',
                                'userid'=>['wangxl','lix','admin','hunjb','wangl'],
                            ],
                            [
                                'id'=>'shouce-ziyou-dpms',
                                'name'=>'DPMS',
                                'userid'=>['wangxl','lix','admin','yanxj','wangl'],
                            ],
                            [
                                'id'=>'shouce-ziyou-omsa',
                                'name'=>'OMSAS',
                                'userid'=>['wangxl','lix','admin','zanghb','wangl'],
                            ],
                            [
                                'id'=>'shouce-ziyou-xdba',
                                'name'=>'XDBA',
                                'userid'=>['wangxl','lix','admin','zanghb','wangl'],
                            ],
                    )
            ],
        )
    ),
    6=>array(
        'id'=>'zhaobiao',
        'name'=>'招标要求',
        'userid'=>['wangxl','lix','admin'],
        'children'=>array(
            [
                'id'=>'zhaobiao_avocent',
                'name'=>'AVOCENT产品',
                'userid'=>['wangxl','lix','admin','wangl','zanghb','liub']
            ],
            [
                'id'=>'zhaobiao_ziyou',
                'name'=>'自有软件产品',
                'userid'=>['wangxl','lix','admin','zanghb','songjc','yanxj','hunjb','liub','wangl']
            ],
            [
                'id'=>'zhaobiao_yingjian',
                'name'=>'自有硬件产品',
                'userid'=>['wangxl','lix','admin','wangl','zanghb','liub']
            ],
        )
    ),
    7=>array(
        'id'=>'zizhi',
        'name'=>'资质证书',
        'userid'=>['wangxl','lix','admin'],
        'children'=>array(
            [
                'id'=>'zizhi_avocent',
                'name'=>'AVOCENT产品',
                'userid'=>['wangxl','lix','admin','liub']
            ],
            [
                'id'=>'zizhi_ziyou',
                'name'=>'昕辰公司资质',
                'userid'=>['wangxl','lix','admin']
            ],
            [
                'id'=>'zizhi_yingjian',
                'name'=>'自有软件产品',
                'userid'=>['wangxl','lix','admin','zanghb','songjc','yanxj','hunjb','liub','wangl']
            ],
        )
    )
);
